<?php

declare(strict_types=1);

return [
    'Tech' => [
        'AI tools for beginners',
        'Budget smartphone comparison 2026',
        'How to make money with coding',
        'Free tools every creator needs',
        'Tech unboxing India',
        'YouTube algorithm explained',
        'Digital marketing for students',
        'Best apps for productivity',
        'Cybersecurity for beginners',
        'How to start a YouTube channel',
    ],
    'Comedy' => [
        'Office life struggles India',
        'Indian parents expectations',
        'Metro train stories',
        'College exam pressure',
        'Arranged marriage jokes',
        'Traffic in Indian cities',
        'IPL season madness',
        'Power cut struggles',
        'Joint family problems',
        'Jugaad culture India',
    ],
    'Finance' => [
        'SIP vs FD comparison',
        'Tax saving tips India',
        'Stock market for beginners',
        'How to save on a ₹30k salary',
        'Credit card mistakes to avoid',
        'Gold vs mutual funds',
        'EPF and PPF explained',
        'Side hustle ideas India',
        'Rent vs buy house India',
        'Budget 2026 impact on you',
    ],
    'Fitness' => [
        'Home workout without equipment',
        'Weight loss diet India',
        'Yoga for beginners',
        'Protein sources vegetarian India',
        'Running tips for beginners',
        'Gym vs calisthenics',
        'Sleep and fitness connection',
        'Mental health and exercise',
        'PCOS diet and exercise',
        'Intermittent fasting India',
    ],
    'Food' => [
        'Street food tour India',
        '5-minute breakfast ideas',
        'Regional cuisine spotlight',
        'Air fryer recipes India',
        'Healthy Indian snacks',
        'Budget meals for students',
        'Traditional recipe with a twist',
        'Monsoon special recipes',
        'Zero-waste cooking tips',
        'Quick tiffin ideas',
    ],
    'Lifestyle' => [
        'Morning routine for productivity',
        'Minimalism Indian home',
        'Sustainable living tips India',
        'Work from home setup',
        'Self-care on a budget',
        'Digital detox challenge',
        'Book recommendations India',
        'Solo travel tips India',
        'Fashion on a budget',
        'Journaling for beginners',
    ],
    'Gaming' => [
        'Free fire tips and tricks',
        'BGMI rank push guide',
        'Best budget gaming phones India',
        'Gaming setup under ₹20k',
        'How to start gaming YouTube',
        'Console vs mobile gaming India',
        'Esports career in India',
        'Popular games trending India',
        'Game review India',
        'How to reduce lag in mobile gaming',
    ],
    'Education' => [
        'UPSC preparation tips',
        'CAT exam strategy',
        'Learn English fluently',
        'Study techniques that work',
        'Government job preparation',
        'Online courses worth it',
        'Scholarship opportunities India',
        'Career after 12th guide',
        'Skill development for jobs',
        'Time management for students',
    ],
];
